# Preface {.unnumbered}

This course offers a survey of common approaches to statistical modeling found in psychology and neuroscience, with three key goals in mind: flexibility, generalizability, and reproducibility. We focus on analytical techniques that are **flexible**, in the sense that they can be adapted to different types of study designs with different types of data. We seek to structure analyses to support claims that are **generalizable** to the larger population of people (and possibly stimuli) from which our sample was drawn. Finally, we aim to analyse data in ways that are **reproducible** by writing plain text scripts in R. In this way, the full set of procedures have been documented in an unambiguous way to enable others (including our future selves!) to easily reproduce our analysis from the raw data to the results and perhaps even up to generating the research report.

This textbook accompanies a one-semester survey course whose aim is to introduce students to the most common analytical approaches in the field. But psychology and neuroscience are broad research areas with many different traditions and approaches, reflecting the complexity of the subject matter. Fortunately, all of these approaches are built on the foundation of linear regression. My hope is to provide a solid foundation in regression so that you know enough to go further on your own with any technique you are interested in. Be under no illusion that we give adequate treatment to techniques introduced in this textbook beyond multiple regression. For each approach, I provide guidance for learning more at the end of the corresponding chapter. 

The textbook focuses on the practical implementation of concepts introduced in lectures of my course. The textbook itself does not provide much conceptual discussion. Nevertheless, it may still be useful for people who already understand these concepts but are looking to learn their implementation in R statistical programming.

## About this book

The material in this course forms the basis for a one-semester course for third-year undergradautes taught by [Dale Barr]() at the [University of Glasgow School of Psychology and Neuroscience](https://www.psy.gla.ac.uk). It is part of the [PsyTeachR series of course materials](https://psyteachr.github.io) developed by University of Glasgow Psychology staff. 

This textbook is meant to be **interactive**. Each chapter contains embedded exercises as well as web applications to help students better understand the content. The interactive content will only work if you access this material through a web browser. Printing out the material is not recommended. 

<!--
If you want to access the textbook without an internet connection or have a local version to keep in case this site changes or moves, you can [download a version for offline use](offline-textbook.zip). Just extract the files from the ZIP archive, go to the `docs` subdirectory, and open the file `index.html` using a web browser.
-->

The main tool that we will be using is the [statistical programming environment R](https://r-project.org). To follow along with the code in this textbook you will need R version 4.2.0 or later. It is also recommended that you install the add-on packages `tidyverse`, `lme4`, `psych`, `corrr`, and `lavaan`.

For anyone starting out with R, you will need to choose an [:Integrated Development Environment](glossary.html#IDE). For beginners, the [RStudio Desktop](https://posit.co/download/rstudio-desktop/) is a good choice. 

### How to use this book

This book has 'dark' and 'light' modes that you can toggle between to suit your reading preferences. Look for the toggle switch next to where the book title is displayed in your browser.

When discussing statistical modeling, some use of technical terminology is unavoidable. This book contains a [glossary](glossary.qmd) where you can find definitions of common terms. I have used the [Nutshell](https://ncase.me/nutshell/) web tool which allows you to "expand" definitions to appear within the body of the web page, to avoid flipping back and forth between the main text and the glossary. Whereever you see an underlined term that has two dots to the top left of it, like this term—[:Nutshell](glossary.qmd#Nutshell)—you can click on the term to expand the definition (try it!).

### How to cite this book {-}

Barr, Dale J. (2024). *Statistical models in psychology and neuroscience: A survey*. Version 0.9.0. Retrieved from <https://psyteachr.github.io/stat-models-v2>.

<!-- 
## Found an issue? {-}

If you find errors or typos, have questions or suggestions, please file an issue at <https://github.com/psyteachr/stat-models-v1/issues>. Thanks!
-->

### Free to re-use and remix! {-}

You are free to re-use and modify the material in this textbook for your own purposes with the stipulation that you cite the original work. Please note additional terms of the [Creative Commons CC-BY-SA 4.0 license](https://creativecommons.org/licenses/by-sa/4.0/) governing re-use of this material.

### How this book was made

This book was authored using the Quarto publishing system. To learn more about Quarto books visit <https://quarto.org/docs/books>.
