<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Correlation and Regression – Statistical Models in Psychology and Neuroscience: A Survey</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./multiple-reg.html" rel="next">
<link href="./intro-placeholder.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-bafd94f2deb1d35dec8254ac31951f16.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-a2d08f8a70a9a46c9db7361725a9e247.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="site_libs/quarto-contrib/nutshell-1.0.7/nutshell.js"></script>
<script src="site_libs/quarto-contrib/nutshell-1.0.7/nutshell_options.js"></script>
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="glossary.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./corr-and-reg.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation and Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistical Models in Psychology and Neuroscience: A Survey</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro-placeholder.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./corr-and-reg.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation and Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multiple-reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Interactions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Mixed-effects models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notation</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#correlation" id="toc-correlation" class="nav-link active" data-scroll-target="#correlation"><span class="header-section-number">2.1</span> Correlation</a>
  <ul class="collapse">
  <li><a href="#bivariate-app" id="toc-bivariate-app" class="nav-link" data-scroll-target="#bivariate-app"><span class="header-section-number">2.1.1</span> Bivariate application</a></li>
  <li><a href="#covariance-matrix" id="toc-covariance-matrix" class="nav-link" data-scroll-target="#covariance-matrix"><span class="header-section-number">2.1.2</span> Covariance matrix</a></li>
  </ul></li>
  <li><a href="#regression" id="toc-regression" class="nav-link" data-scroll-target="#regression"><span class="header-section-number">2.2</span> Regression</a>
  <ul class="collapse">
  <li><a href="#scatterplot" id="toc-scatterplot" class="nav-link" data-scroll-target="#scatterplot"><span class="header-section-number">2.2.1</span> Scatterplot</a></li>
  <li><a href="#fitting-a-model-using-lm" id="toc-fitting-a-model-using-lm" class="nav-link" data-scroll-target="#fitting-a-model-using-lm"><span class="header-section-number">2.2.2</span> Fitting a model using <code>lm()</code></a></li>
  <li><a href="#plotting-the-model-fit-against-the-data" id="toc-plotting-the-model-fit-against-the-data" class="nav-link" data-scroll-target="#plotting-the-model-fit-against-the-data"><span class="header-section-number">2.2.3</span> Plotting the model fit against the data</a></li>
  <li><a href="#getting-other-properties-of-fitted-model-objects" id="toc-getting-other-properties-of-fitted-model-objects" class="nav-link" data-scroll-target="#getting-other-properties-of-fitted-model-objects"><span class="header-section-number">2.2.4</span> Getting other properties of fitted model objects</a></li>
  </ul></li>
  <li><a href="#relationship-between-correlation-and-regression" id="toc-relationship-between-correlation-and-regression" class="nav-link" data-scroll-target="#relationship-between-correlation-and-regression"><span class="header-section-number">2.3</span> Relationship between correlation and regression</a></li>
  <li><a href="#two-approaches-for-simulating-bivariate-data" id="toc-two-approaches-for-simulating-bivariate-data" class="nav-link" data-scroll-target="#two-approaches-for-simulating-bivariate-data"><span class="header-section-number">2.4</span> Two approaches for simulating bivariate data</a>
  <ul class="collapse">
  <li><a href="#approach-1-simulating-from-the-covariance-matrix" id="toc-approach-1-simulating-from-the-covariance-matrix" class="nav-link" data-scroll-target="#approach-1-simulating-from-the-covariance-matrix"><span class="header-section-number">2.4.1</span> Approach 1: Simulating from the covariance matrix</a></li>
  <li><a href="#approach-2-simulating-from-the-regression-model" id="toc-approach-2-simulating-from-the-regression-model" class="nav-link" data-scroll-target="#approach-2-simulating-from-the-regression-model"><span class="header-section-number">2.4.2</span> Approach 2: Simulating from the regression model</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Correlation and Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="correlation" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="correlation"><span class="header-section-number">2.1</span> Correlation</h2>
<p>A correlation coefficient quantifies the <strong>strength</strong> and <strong>direction</strong> of an association between two variables. It is usually represented by the symbol <span class="math inline">\(r\)</span> or <span class="math inline">\(\rho\)</span> (Greek letter “rho”). The correlation coefficient ranges between -1 and 1, with 0 corresponding to no relationship, positive values reflecting a positive relationship (as one variable increases, so does the other), and negative values reflecting a negative relationship (as one variable increases, the other decreases).</p>
<p>The web app below shows 100 random points from a bivariate normal distribution for variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. You can use the sliders to change the parameters of that distribution: the correlation (Greek symbol <span class="math inline">\(\rho\)</span>, “rho”), the standard deviation for <span class="math inline">\(X\)</span> (<span class="math inline">\(\sigma_X\)</span>, “sigma X”), the standard deviation for <span class="math inline">\(Y\)</span> (<span class="math inline">\(\sigma_Y\)</span>), the mean of <span class="math inline">\(X\)</span> (<span class="math inline">\(\mu_X\)</span>, “mu X”) and the mean of <span class="math inline">\(Y\)</span> (<span class="math inline">\(\mu_Y\)</span>, “mu Y”). These five parameters are all you need to characterize a bivariate normal distribution.</p>
<p>Play around with the sliders until you have a conceptual understanding of the various parameters. Use the “new sample” button to get a new set of 100 randomly-generated pairs, and use “reset” to reset the parameter values to their defaults.</p>
<section id="bivariate-app" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="bivariate-app"><span class="header-section-number">2.1.1</span> Bivariate application</h3>
<iframe src="https://dalejbarr.github.io/bivariate/index.html" width="420" height="620" style="border: none;">
</iframe>
<p>There are different correlation coefficients that make different assumptions or that allow you to work with different types of data. To start, let’s consider the one most commonly used: the <em>Pearson product-moment correlation coefficient,</em> which can be applied to <a href="./glossary.html#interval-scale">:interval</a> or <a href="./glossary.html#ratio-scale">:ratio</a> scale data. When you hear someone talk about a “correlation” without further qualification, they are most likely talking about a Pearson correlation coefficient. If we have the variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> then we might use <span class="math inline">\(r_{XY}\)</span> or <span class="math inline">\(\rho_{XY}\)</span> as a symbol for the correlation.</p>
<p>There are multiple equivalent formulas for calculating a Pearson correlation coefficient. The most important one for us is</p>
<p><span class="math display">\[r_{XY} = \frac{cov_{XY}}{S_X S_Y}\]</span></p>
<p>because it can offer some conceptual understanding. The quantity <span class="math inline">\(cov_{XY}\)</span> is the covariance between two variables, <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, which is defined as</p>
<p><span class="math display">\[cov_{XY} = \frac{\Sigma (X - \bar{X})(Y - \bar{Y})}{N}.\]</span></p>
<p>In other words, it is the sum of the products of the deviation scores for each <span class="math inline">\((X, Y)\)</span> pair of observations divided by the number of pairs.</p>
<p>Note that the covariance of a variable with itself is</p>
<p><span class="math display">\[cov_{XX} = \frac{\Sigma (X - \bar{X})(X - \bar{X})}{N} = \frac{\Sigma (X - \bar{X})^2}{N}\]</span></p>
<p>which is the formula for the variance of a variable. Taking the square root gives us the formula for the standard deviation:</p>
<p><span class="math display">\[SD_X = \sqrt{\frac{\Sigma (X - \bar{X})^2}{N}}.\]</span></p>
<p>The above formulas are for calculating these statistics for the sample. When we want to estimate the corresponding parameters for the population we have sampled from, these formulas will have <span class="math inline">\(N-1\)</span> instead of <span class="math inline">\(N\)</span> in their denominators. The R functions <code>cov()</code>, <code>var()</code>, and <code>sd()</code> are used to compute these values on vectors or matrices.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: Calculate a correlation coefficient for variables in a data frame.
</div>
</div>
<div class="callout-body-container callout-body">
<p>The data frame <code>iris</code> in R has measurements of different parts of 50 flowers from three different species of iris. See <code>help("iris")</code> for more information about this dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris, <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1          5.1         3.5          1.4         0.2  setosa
2          4.9         3.0          1.4         0.2  setosa
3          4.7         3.2          1.3         0.2  setosa
4          4.6         3.1          1.5         0.2  setosa
5          5.0         3.6          1.4         0.2  setosa
6          5.4         3.9          1.7         0.4  setosa</code></pre>
</div>
</div>
<p>Calculate the correlation between the petal length and petal width of these flowers in R using the <code>cov()</code> and <code>sd()</code> functions in R.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[r_{XY} = \frac{cov_{XY}}{S_X S_Y}\]</span></p>
<pre><code>cov(iris$Petal.Length, iris$Petal.Width) # covariance</code></pre>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(iris<span class="sc">$</span>Petal.Length, iris<span class="sc">$</span>Petal.Width) <span class="sc">/</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  (<span class="fu">sd</span>(iris<span class="sc">$</span>Petal.Length) <span class="sc">*</span> <span class="fu">sd</span>(iris<span class="sc">$</span>Petal.Width))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9628654</code></pre>
</div>
</div>
<p>Let’s compare this result with the result of the function <code>cor()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(iris<span class="sc">$</span>Petal.Length, iris<span class="sc">$</span>Petal.Width)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9628654</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="covariance-matrix" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="covariance-matrix"><span class="header-section-number">2.1.2</span> Covariance matrix</h3>
<p><strong>Covariance matrices become very important once we start talking about multilevel modelling and multivariate analyses.</strong></p>
<p>A covariance matrix (also known as the <strong>variance-covariance</strong> matrix) is a mathematical structure that describes the spread of a multivariate distribution. It is multidimensional analogue of the <strong>standard deviation</strong>.</p>
<p>To fully describe a univariate (single variable) normal distribution, you need to know only two parameters: the mean (<span class="math inline">\(\mu\)</span>) and standard deviation (<span class="math inline">\(\sigma\)</span>). Mathematically, this is often represented as</p>
<p><span class="math display">\[X_i \sim \mathcal{N}\left(\mu, \sigma^2\right)\]</span></p>
<p>which is read as, “each case <span class="math inline">\(i\)</span> of the <span class="math inline">\(X\)</span> variable is drawn from a normal distribution with mean of <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>.</p>
<p>To fully describe a bivariate normal distribution, you need five parameters: the means of each of the two variables, their standard deviations, and their correlation. The mathematical way to represent the idea that pairs of observations for case <span class="math inline">\(i\)</span>, (<span class="math inline">\(X_i\)</span>, <span class="math inline">\(Y_i\)</span>) are drawn from a normal distribution is:</p>
<p><span class="math display">\[\begin{pmatrix} X_i \\ Y_i\end{pmatrix} \sim \mathcal{N}\left(\begin{pmatrix}\mu_X \\ \mu_Y\end{pmatrix}, \mathbf{\Sigma}\right)\]</span></p>
<p>where <span class="math inline">\(\mathbf{\Sigma}\)</span> is a covariance matrix, defined as</p>
<p><span class="math display">\[\mathbf{\Sigma} = \begin{pmatrix}cov_{xx} &amp; cov_{xy} \\ cov_{yx} &amp; cov_{yy}\end{pmatrix} = \begin{pmatrix}\rho_{xx}\sigma_x\sigma_x &amp; \rho_{xy}\sigma_x\sigma_y \\ \rho_{yx}\sigma_y\sigma_x &amp; \rho_{yy}\sigma_y\sigma_y\end{pmatrix}.\]</span></p>
<p>You can see that the entries are just a rearrangement of the correlation formula</p>
<p><span class="math display">\[\rho_{xy} = \frac{cov_{xy}}{\sigma_x \sigma_y}.\]</span></p>
<p>where we rearrange to solve for <span class="math inline">\(cov_{xy}\)</span></p>
<p><span class="math display">\[cov_{xy} = \rho_{xy}\sigma_x \sigma_y.\]</span></p>
<p>Because the correlation of a variable with itself (<span class="math inline">\(\rho_{xx}\)</span>, <span class="math inline">\(\rho_{yy}\)</span>) is always 1, we will often see <span class="math inline">\(\mathbf{\Sigma}\)</span> written equivalently as</p>
<p><span class="math display">\[\begin{pmatrix}{\sigma_x}^2 &amp; \rho_{xy}\sigma_x\sigma_y \\ \rho_{yx}\sigma_y\sigma_x &amp; {\sigma_y}^2\end{pmatrix}.\]</span></p>
<p>Note two things about the above matrix: first, the variances appear in the main diagonal, and the covariance appear off the main diagonal. Second, a correlation is not directional, and so <span class="math inline">\(\rho_{xy} = \rho_{yx}\)</span>, which means that the two off-diagonal elements have the same value.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning: <span class="math inline">\(\Sigma\)</span> doing double duty
</div>
</div>
<div class="callout-body-container callout-body">
<p>You may have noticed that the Greek capital letter <span class="math inline">\(\Sigma\)</span> is used both to represent the instruction to add things together, e.g., <span class="math inline">\(\Sigma X\)</span> = <code>sum(X)</code>, and now it’s being used as a symbol to represent a covariance matrix <span class="math inline">\(\mathbf{\Sigma}\)</span>. In the latter case, <span class="math inline">\(\Sigma\)</span> appears in boldface (compare <span class="math inline">\(\mathbf{\Sigma}\)</span> to <span class="math inline">\(\Sigma\)</span>). Usually the context will make things clear.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tell me more about matrices
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>In mathematics, matrices are just generalizations of the concept of a vector: a vector can be thought of as having one dimension, whereas a matrix can have any number of dimensions.</p>
<p>So the matrix</p>
<p><span class="math display">\[
\begin{pmatrix}
1 &amp; 4 &amp; 7 \\
2 &amp; 5 &amp; 8 \\
3 &amp; 6 &amp; 9 \\
\end{pmatrix}
\]</span></p>
<p>is a 3 (row) by 3 (column) matrix containing the column vectors <span class="math inline">\(\begin{pmatrix} 1 \\ 2 \\ 3 \\ \end{pmatrix}\)</span>, <span class="math inline">\(\begin{pmatrix} 4 \\ 5 \\ 6 \\ \end{pmatrix}\)</span>, and <span class="math inline">\(\begin{pmatrix} 7 \\ 8 \\ 9 \\ \end{pmatrix}\)</span>. Conventionally, we refer to matrices in <span class="math inline">\(i\)</span> by <span class="math inline">\(j\)</span> format, with <span class="math inline">\(i\)</span> being the number of rows and <span class="math inline">\(j\)</span> being the number of columns. So a 3x2 matrix has 3 rows and 2 columns, like so.</p>
<p><span class="math display">\[
\begin{pmatrix}
a &amp; d \\
b &amp; e \\
c &amp; f \\
\end{pmatrix}
\]</span></p>
<p>A <strong>square matrix</strong> is a matrix where the number of rows is equal to the number of columns.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: Generate a covariance matrix
</div>
</div>
<div class="callout-body-container callout-body">
<p>Generate a covariance matrix corresponding to the relation between <code>Petal.Width</code> and <code>Petal.Length</code> for the <code>iris</code> dataset. Name your covariance matrix <code>cvmx</code>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>r_wl <span class="ot">&lt;-</span> <span class="fu">cor</span>(iris<span class="sc">$</span>Petal.Width, iris<span class="sc">$</span>Petal.Length)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>sd_w <span class="ot">&lt;-</span> <span class="fu">sd</span>(iris<span class="sc">$</span>Petal.Width)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>sd_l <span class="ot">&lt;-</span> <span class="fu">sd</span>(iris<span class="sc">$</span>Petal.Length)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>cov_wl <span class="ot">&lt;-</span> r_wl <span class="sc">*</span> sd_w <span class="sc">*</span> sd_l</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="do">## bind together rows of the matrix using rbind()</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>cvmx <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">c</span>(sd_w<span class="sc">^</span><span class="dv">2</span>, cov_wl),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>              <span class="fu">c</span>(cov_wl, sd_l<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>cvmx</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]     [,2]
[1,] 0.5810063 1.295609
[2,] 1.2956094 3.116278</code></pre>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="regression" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="regression"><span class="header-section-number">2.2</span> Regression</h2>
<p>When we have two variables, <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, and our goal is to predict values of <span class="math inline">\(Y\)</span> from <span class="math inline">\(X\)</span>, then we usually want to fit a <strong>linear regression</strong> model; or we might say, we want “to regress <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span>.”</p>
<p>A simple regression model is of the form:</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_i + e_i.\]</span></p>
<p>In this equation, <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the y-intercept and slope parameters respectively, and the <span class="math inline">\(e_i\)</span>s are the errors (the part of each <span class="math inline">\(Y_i\)</span> left unexplained by the model). It is conventionally assumed that the <span class="math inline">\(e_i\)</span> values are from a normal distribution with mean of zero and variance <span class="math inline">\(\sigma^2\)</span>; the math-y way of saying this is <span class="math inline">\(e_i \sim \mathcal{N}(0, \sigma^2)\)</span>, where <span class="math inline">\(\sim\)</span> is read as “distributed according to” and <span class="math inline">\(\mathcal{N}(0, \sigma^2)\)</span> means “Normal distribution (<span class="math inline">\(\mathcal{N}\)</span>) with mean of 0 and variance of <span class="math inline">\(\sigma^2\)</span>”.</p>
<section id="scatterplot" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="scatterplot"><span class="header-section-number">2.2.1</span> Scatterplot</h3>
<p>Let’s return to the <code>iris</code> data. Say we want to predict <code>Petal.Length</code> from <code>Petal.Width</code>. Before proceeding, it is a good idea to make a scatterplot of the data using ggplot2. We can use the <code>colour</code> aesthetic to capture what species a datapoint belongs to.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(iris,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Petal.Width, <span class="at">y =</span> Petal.Length, <span class="at">colour =</span> Species)) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-iris" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-iris-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="corr-and-reg_files/figure-html/fig-iris-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iris-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Scatterplot of the <code>iris</code> data.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The plot looks like we could nicely fit a line through the cloud of points. Let’s do that.</p>
</section>
<section id="fitting-a-model-using-lm" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="fitting-a-model-using-lm"><span class="header-section-number">2.2.2</span> Fitting a model using <code>lm()</code></h3>
<p>We use the <code>lm()</code> function (<code>l</code>inear <code>m</code>odel) to fit regression models. It’s a good idea to look at the help file before using a function we’re unfamiliar with (type <code>help("lm")</code> in the console).</p>
<pre><code>lm                    package:stats                    R Documentation

Fitting Linear Models

Description:

     ‘lm’ is used to fit linear models, including multivariate ones.
     It can be used to carry out regression, single stratum analysis of
     variance and analysis of covariance (although aov may provide a
     more convenient interface for these).

Usage:

     lm(formula, data, subset, weights, na.action,
        method = "qr", model = TRUE, x = FALSE, y = FALSE, qr = TRUE,
        singular.ok = TRUE, contrasts = NULL, offset, ...)
     
     ## S3 method for class 'lm'
     print(x, digits = max(3L, getOption("digits") - 3L), ...)
     
Arguments:

 formula: an object of class ‘"formula"’ (or one that can be coerced to
          that class): a symbolic description of the model to be
          fitted.  The details of model specification are given under
          ‘Details’.

    data: an optional data frame, list or environment (or object
          coercible by as.data.frame to a data frame) containing the
          variables in the model.  If not found in ‘data’, the
          variables are taken from ‘environment(formula)’, typically
          the environment from which ‘lm’ is called.</code></pre>
<p>Usually the first few arguments are the important ones we need to pay attention to. Here, the key ones are <code>formula</code> and <code>data</code>. We need to provide a symbolic description of the model. Under <code>Details</code> we see</p>
<pre><code>Details:

     Models for ‘lm’ are specified symbolically.  A typical model has
     the form ‘response ~ terms’ where ‘response’ is the (numeric)
     response vector and terms is a series of terms which specifies a
     linear predictor for ‘response’.</code></pre>
<p>So we specify the model using <code>response ~ terms</code>, but we omit the intercept and the error term of the model because they are always implied. We also don’t name the regression coefficients; they get given the same names as the predictor variables. Thus our formula <span class="math inline">\(Y_i = \beta_0 + \beta_1 X_i + e_i\)</span> just becomes <code>Petal.Length ~ Petal.Width</code>. The <code>data</code> argument tells the function the name of the data frame where the variables can be found. The result of the call to <code>lm()</code> is a fitted model object. We want to store the result so that we can perform further computations on the object. So altogether, our call might look like the following.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Petal.Length <span class="sc">~</span> Petal.Width, <span class="at">data =</span> iris)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that we chose the name <code>mod</code>, but this is arbitrary; we could have used any other variable name.</p>
<p>To see the results of the function, we use <code>summary()</code> on the model object.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Petal.Length ~ Petal.Width, data = iris)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.33542 -0.30347 -0.02955  0.25776  1.39453 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  1.08356    0.07297   14.85   &lt;2e-16 ***
Petal.Width  2.22994    0.05140   43.39   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4782 on 148 degrees of freedom
Multiple R-squared:  0.9271,    Adjusted R-squared:  0.9266 
F-statistic:  1882 on 1 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We are most interested in the table of coefficients here, which is the table of the regression coefficients for our model, the y-intercept <span class="math inline">\(\beta_0\)</span> and the slope <span class="math inline">\(\beta_1\)</span>. We get <span class="math inline">\(\hat{\beta}_0 = 1.084\)</span> and <span class="math inline">\(\hat{\beta}_1 = 2.230\)</span>. So with every 1 unit increase in <code>Petal.Width</code>, <code>Petal.Length</code> increases by 2.230.</p>
<p>We can see these value in the output, but we can also pull them out using code with the <code>coef()</code> function, which returns a vector with their values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) Petal.Width 
   1.083558    2.229940 </code></pre>
</div>
</div>
<p>Recall that the errors in our model are from a normal distribution with a mean of zero and variance <span class="math inline">\(\sigma^2\)</span>, stated mathematically as <span class="math inline">\(e_i \sim \mathcal{N}\left(0, \sigma^2\right)\)</span>. The “residual standard error” for the model tells us <span class="math inline">\(\hat{\sigma}\)</span>, the estimated value of <span class="math inline">\(\sigma\)</span>. We can pull this out of the model object using the <code>sigma()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sigma</span>(mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4782058</code></pre>
</div>
</div>
</section>
<section id="plotting-the-model-fit-against-the-data" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="plotting-the-model-fit-against-the-data"><span class="header-section-number">2.2.3</span> Plotting the model fit against the data</h3>
<p>It’s usually a good idea to plot the model fit against the data to see how well we are doing. Let’s re-create our scatterplot but use <code>geom_abline()</code> to add in a line with the slope and y-intercept for the model, which we can get using <code>coef()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(iris,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> Petal.Width, <span class="at">y =</span> Petal.Length, <span class="at">colour =</span> Species)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="fu">coef</span>(mod)[<span class="st">"Petal.Width"</span>],</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">intercept =</span> <span class="fu">coef</span>(mod)[<span class="st">"(Intercept)"</span>],</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">colour =</span> <span class="st">"pink"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="corr-and-reg_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="getting-other-properties-of-fitted-model-objects" class="level3" data-number="2.2.4">
<h3 data-number="2.2.4" class="anchored" data-anchor-id="getting-other-properties-of-fitted-model-objects"><span class="header-section-number">2.2.4</span> Getting other properties of fitted model objects</h3>
<p>There are three other functions that useful to know. Each of these takes the fitted model object as the first argument.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>function</th>
<th>description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>predict()</code></td>
<td>generate predictions from the model</td>
</tr>
<tr class="even">
<td><code>fitted()</code></td>
<td>get fitted values from the model</td>
</tr>
<tr class="odd">
<td><code>residuals()</code></td>
<td>calculate residuals</td>
</tr>
</tbody>
</table>
<p>Fitted values, denoted by <span class="math inline">\(\hat{Y}_i\)</span>, are the predicted values for all the <span class="math inline">\(X_i\)</span> in the data. Predicted values can be for any <span class="math inline">\(X_i\)</span> values, even those not seen in the dataset.</p>
<p>Residuals represent the error of prediction, and are defined as <span class="math inline">\(Y_i - \hat{Y}_i\)</span>; i.e., the observed value for case <span class="math inline">\(i\)</span> minus the fitted value for case <span class="math inline">\(i\)</span>.</p>
<!-- TODO exercise: calculate residuals without using residuals() -->
</section>
</section>
<section id="relationship-between-correlation-and-regression" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="relationship-between-correlation-and-regression"><span class="header-section-number">2.3</span> Relationship between correlation and regression</h2>
<p>We can calculate regression coefficients from correlation statistics and vice versa. To get regression statistics from correlation statistics, along with the correlation coefficient we need means of X and Y (denoted by <span class="math inline">\(\mu_x\)</span> and <span class="math inline">\(\mu_y\)</span> respectively) and their standard deviations (<span class="math inline">\(\hat{\sigma}_x\)</span> and <span class="math inline">\(\hat{\sigma}_y\)</span>). Let’s see how we can compute regression coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
<p>First, the slope of the regression line <span class="math inline">\(\beta_1\)</span> equals the correlation coefficient <span class="math inline">\(\rho\)</span> times the ratio of the standard deviations of <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>.</p>
<p><span class="math display">\[\beta_1 = \rho \frac{\sigma_Y}{\sigma_X}\]</span></p>
<p>If you play around with the <a href="#bivariate-app">bivariate web app</a> you can verify for yourself that this is the case.</p>
<p>The next thing to note is that for mathematical reasons, the regression line is guaranteed to go through the point corresponding to the mean of <span class="math inline">\(X\)</span> and the mean of <span class="math inline">\(Y\)</span>, i.e., the point <span class="math inline">\((\mu_x, \mu_y)\)</span>. (You can think of the regression line “pivoting” around that point depending on the slope). You also know that <span class="math inline">\(\beta_0\)</span> is the y-intercept, the point where the line crosses the vertical axis at <span class="math inline">\(X = 0\)</span>. From this information, and the estimates above, can you figure out the value of <span class="math inline">\(\beta_0\)</span>?</p>
<p>Well, for each unit increase in <span class="math inline">\(X\)</span> you have a corresponding change of <span class="math inline">\(\beta_1\)</span> for <span class="math inline">\(Y\)</span>, and you know that the line goes through the points <span class="math inline">\((\mu_x, \mu_y)\)</span> as well as the y-intercept <span class="math inline">\((0, \beta_0)\)</span>.</p>
<p>Think about stepping back unit-by-unit from <span class="math inline">\(X = \mu_x\)</span> to <span class="math inline">\(X = 0\)</span>. At <span class="math inline">\(X = \mu_x\)</span>, <span class="math inline">\(Y = \mu_y\)</span>. Each unit step you take backward in the X dimension, <span class="math inline">\(Y\)</span> will drop by <span class="math inline">\(\beta_1\)</span> units. When you get to zero, <span class="math inline">\(Y\)</span> will have dropped from <span class="math inline">\(\mu_y\)</span> to <span class="math inline">\(\mu_y - \mu_x\beta_1\)</span>.</p>
<p>So the general solution is: <span class="math inline">\(\beta_0 = \mu_y - \mu_x\beta_1\)</span>.</p>
<p>To close, here are a few implications from the relationship between correlation and regression.</p>
<ul>
<li><span class="math inline">\(\beta_1 = 0\)</span> is the same as <span class="math inline">\(\rho = 0\)</span>.</li>
<li><span class="math inline">\(\beta_1 &gt; 0\)</span> implies <span class="math inline">\(\rho &gt; 0\)</span>, since standard deviations can’t be negative.</li>
<li><span class="math inline">\(\beta_1 &lt; 0\)</span> implies <span class="math inline">\(\rho &lt; 0\)</span>, for the same reason.</li>
<li>Rejecting the null hypothesis that <span class="math inline">\(\beta_1 = 0\)</span> is the same as rejecting the null hypothesis that <span class="math inline">\(\rho = 0\)</span>. The p-values that you get for <span class="math inline">\(\beta_1\)</span> in <code>lm()</code> will be the same as the one you get for <span class="math inline">\(\rho\)</span> from <code>cor.test()</code>.</li>
</ul>
</section>
<section id="two-approaches-for-simulating-bivariate-data" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="two-approaches-for-simulating-bivariate-data"><span class="header-section-number">2.4</span> Two approaches for simulating bivariate data</h2>
<section id="approach-1-simulating-from-the-covariance-matrix" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="approach-1-simulating-from-the-covariance-matrix"><span class="header-section-number">2.4.1</span> Approach 1: Simulating from the covariance matrix</h3>
<p>You can simulate data from the normal distribution using the function <code>rnorm()</code>. The function <code>rnorm()</code> allows you to specify the mean and standard deviation of a single variable. How do we simulate correlated variables?</p>
<p>It should be clear that you can’t just run <code>rnorm()</code> twice and combine the variables, because then you end up with two variables that are unrelated, i.e., with a correlation of zero.</p>
<p>The package <strong><code>MASS</code></strong> provides a function <code>mvrnorm()</code> which is the ‘multivariate’ version of rnorm (hence the function name, <code>mv</code> + <code>rnorm</code>, which makes it easy to remember.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong><code>MASS</code></strong> package comes pre-installed with R. But the only function you’ll probably ever want to use from <strong><code>MASS</code></strong> is <code>mvrnorm()</code>, so rather than load in the package using <code>library("MASS")</code>, it is preferable to use <code>MASS::mvrnorm()</code>, especially as <strong><code>MASS</code></strong> and the <strong><code>dplyr</code></strong> package from <strong><code>tidyverse</code></strong> don’t play well together, due to both packages having the function <code>select()</code>. So if you load in <strong><code>MASS</code></strong> after you load in <strong><code>tidyverse</code></strong>, you’ll end up getting the <strong><code>MASS</code></strong> version of <code>select()</code> instead of the <strong><code>dplyr</code></strong> version. It will do your head in trying to figure out what is wrong with your code, so always use <code>MASS::mvrnorm()</code> without loading <code>library("MASS")</code>.</p>
</div>
</div>
<p>Have a look at the documentation for the <code>mvrnorm()</code> function (type <code>?MASS::mvrnorm</code> in the console).</p>
<p>There are three arguments to take note of:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 93%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">arg</th>
<th style="text-align: left;">description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n</td>
<td style="text-align: left;">the number of samples required</td>
</tr>
<tr class="even">
<td style="text-align: left;">mu</td>
<td style="text-align: left;">a vector giving the means of the variables</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sigma</td>
<td style="text-align: left;">a positive-definite symmetric matrix specifying the covariance matrix of the variables.</td>
</tr>
</tbody>
</table>
<p>The <code>Sigma</code> argument to <code>MASS::mvrnorm()</code> plays an analogous role to the <code>sd</code> argument in <code>rnorm()</code>; it specifies the spread for the two variables.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise: Simulate bivariate data using <code>MASS::mvrnorm()</code>.
</div>
</div>
<div class="callout-body-container callout-body">
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">

</div>
</div>
</div>
</div>
</div>
</section>
<section id="approach-2-simulating-from-the-regression-model" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="approach-2-simulating-from-the-regression-model"><span class="header-section-number">2.4.2</span> Approach 2: Simulating from the regression model</h3>
<p>Another way you can simulated data is based on a regression model. This way is pretty straightforward because we just follow the <span class="math inline">\(Y_i = \beta_0 + \beta_1 X_i + e_i\)</span> formula.</p>
<ul>
<li>first, simulate the <span class="math inline">\(X_i\)</span> values</li>
<li>calculate the predicted value from the model</li>
<li>add random error to the prediction using <code>rnorm()</code> to yield <span class="math inline">\(Y_i\)</span></li>
</ul>
<p>Let’s use this approach to simulate data from the <code>iris</code> dataset. First, let’s get the coefficients and the estimate of <span class="math inline">\(\sigma\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>iris_coef <span class="ot">&lt;-</span> <span class="fu">coef</span>(mod)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>iris_sig <span class="ot">&lt;-</span> <span class="fu">sigma</span>(mod) </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>iris_coef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) Petal.Width 
   1.083558    2.229940 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>iris_sig</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4782058</code></pre>
</div>
</div>
<p>We want to start by creating a data frame containing the <span class="math inline">\(X_i\)</span> values. But for this we need to know <span class="math inline">\(\mu_x\)</span> and <span class="math inline">\(\sigma_x\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>iris_mu_x <span class="ot">&lt;-</span> <span class="fu">mean</span>(iris<span class="sc">$</span>Petal.Width)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>iris_sd_x <span class="ot">&lt;-</span> <span class="fu">sd</span>(iris<span class="sc">$</span>Petal.Width)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We’ll create the <span class="math inline">\(X_i\)</span> values in a vector first. We have to decide on the number of paired observations we want; let’s say 150, the same number as in the original dataset. Let’s set the seed before we do any random number generation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1451</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>iris_x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">150</span>, <span class="at">mean =</span> iris_mu_x, <span class="at">sd =</span> iris_sd_x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s use the <code>tibble()</code> function (from tidyverse) to create the <span class="math inline">\(X_i\)</span> values in a data frame, followed by the predicted value, <code>y_hat</code>, followed by the errors, <code>e_i</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>sim_iris <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">x_i =</span> iris_x,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y_hat =</span> iris_coef[<span class="dv">1</span>] <span class="sc">+</span> iris_coef[<span class="dv">2</span>] <span class="sc">*</span> x_i,</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">e_i =</span> <span class="fu">rnorm</span>(<span class="dv">150</span>, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> iris_sig),</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y_i =</span> y_hat <span class="sc">+</span> e_i)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s have a look.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(sim_iris,</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> x_i, <span class="at">y =</span> y_i)) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="corr-and-reg_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This looks fairly similar to the original data, but note that we haven’t taken into account the species of flower, so the points are spread evenly across the x dimension, unlike in Figure <a href="#fig-iris" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> above. So our model is good, but not really complete.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./intro-placeholder.html" class="pagination-link" aria-label="Introduction">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./multiple-reg.html" class="pagination-link" aria-label="Multiple regression">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Multiple regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>